
# Host format:
# 172.1.1.2 clusterhost=redis01

[all:vars]

[master]
#172.24.32.82  clusterhost=master

[redis_nodes:children]
master

[redis_nodes]
#172.24.32.83 clusterhost=redis01
#172.24.32.84 clusterhost=redis02
#172.24.32.85 clusterhost=redis03
