---
- name: Install python apt... Hell yeah ubuntu
  shell: apt-get update; apt-get install python-apt -y

- name: Ensure required packages are installed
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - ruby
    - vim

- name: Place the redis.conf file on all hosts
  copy: src=redis.conf dest=/etc/redis.conf

- name: Ensure /var/log/redis/ exists
  file: path=/var/log/redis owner=root group=root mode=0655 state=directory

- name: Ensure /var/lib/redis/ exsists
  file: path=/var/lib/redis owner=root group=root mode=0655 state=directory

- name: Place the redis files on each server
  get_url: url=https://github.com/antirez/redis/archive/3.0.0-rc4.tar.gz dest=/root/3.0.0-rc4.tar.gz validate_certs=no

- name: Untar redis files
  unarchive: src=/root/3.0.0-rc4.tar.gz dest=/root/ copy=no

- name: Make install redis bins
  shell: make install chdir=/root/redis-3.0.0-rc4/

- name: Open port 6379
  ufw: rule=allow port=6379 proto=tcp

- name: open port 16379
  ufw: rule=allow port=16379 proto=tcp

- name: Start redis
  command: redis-server /etc/redis.conf
