---
 - name: Ensure required packages are installed
  apt: name={{ item }} state=present
  with_items:
    - build-essentials
    - ruby
    - rubygems
    - vim

- name: Copy SSH key from master node to all hosts
  authorized_key: user=root key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: Place the redis.conf file on all hosts
  copy: src=redis.conf dest=/etc/redis.conf

- name: Ensure /var/log/redis/ exists
  file: path=/var/log/redis owner=root group=root mode=0655 state=directory

- name: Ensure /var/lib/redis/ exsists
  file: path=/var/lib/redis owner=root group=root mode=0655 state=directory

- name: Place the redis files on each server
  get_url: url=https://github.com/antirez/redis/archive/3.0.0-rc4.tar.gz dest=~

- name: Untar redis files
  unarchive: src=/root/3.0.0-rc4.tar.gz dest=~

- name: Make install redis bins
  shell: make install chdir=~/redis-3.0.0-rc4/

- name: Open up port 6379 on iptables (Keeping in for Ubuntu)
  shell: iptables -I INPUT -p tcp --dport 6379 -j ACCEPT; service iptables save; service iptables reload

- name: Open up port 6379 on iptables (Keeping in for Ubuntu)
  shell: iptables -I INPUT -p tcp --dport 16379 -j ACCEPT; service iptables save; service iptables reload

- name: Start redis
  command: redis-server /etc/redis.conf
